FROM node:20-alpine3.17

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install

COPY ./server ./server
COPY ./tsconfig.json ./tsconfig.json
COPY ./jest.config.js ./jest.config.js
COPY ./.env ./.env

CMD ["yarn", "test"]
